# Generated by Django 4.2.4 on 2023-08-17 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proudct',
            new_name='product',
        ),
    ]
